export const colors = [
    { name: "Pink", hex: "#FFC0CB" },
    { name: "Red", hex: "#FF0000" },
    { name: "Blue", hex: "#0000FF" },
    { name: "Green", hex: "#008000" },
    { name: "Yellow", hex: "#FFFF00" },
    { name: "Orange", hex: "#FFA500" },
    { name: "Purple", hex: "#800080" },
    { name: "Cyan", hex: "#00FFFF" },
    { name: "Magenta", hex: "#FF00FF" },
    { name: "Lime", hex: "#00FF00" },
    { name: "Teal", hex: "#008080" },
    { name: "Lavender", hex: "#E6E6FA" },
    { name: "Brown", hex: "#A52A2A" },
    { name: "Beige", hex: "#F5F5DC" },
    { name: "Maroon", hex: "#800000" },
    { name: "Mint", hex: "#98FF98" },
    { name: "Olive", hex: "#808000" },
    { name: "Coral", hex: "#FF7F50" },
    { name: "Navy", hex: "#000080" },
    { name: "Grey", hex: "#808080" },
    { name: "Turquoise", hex: "#40E0D0" },
    { name: "Violet", hex: "#EE82EE" },
    { name: "Gold", hex: "#FFD700" },
    { name: "Peach", hex: "#FFDAB9" },
    { name: "Indigo", hex: "#4B0082" },
    { name: "Amber", hex: "#FFBF00" },
    { name: "Crimson", hex: "#DC143C" },
    { name: "Plum", hex: "#DDA0DD" },
    { name: "Sky Blue", hex: "#87CEEB" },
    { name: "Khaki", hex: "#F0E68C" },
    { name: "Rose", hex: "#FF007F" },
    { name: "Charcoal", hex: "#36454F" },
    { name: "Ivory", hex: "#FFFFF0" },
    { name: "Salmon", hex: "#FA8072" },
    { name: "Periwinkle", hex: "#CCCCFF" },
    { name: "Mustard", hex: "#FFDB58" }
  ];
  
  export default colors;